=== VMatt013/University/Webtech/Gyak5/frankfurter-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema for the frankfurter API",
    "type": "object",
    "properties": {
        "amount": {"type": "number"},
        "base": {
            "type": "string",
            "pattern": "^[A-Z]{3}$"
        },
        "date":{
            "type": "string",
            "format": "date"
        },
        "rates":{
            "type": "object",
            "patternProperties": {
                "^[A-Z{3}$]": {"type": "number"}
            },
            "additionalProperties": false
        }
    },
    "required": ["amount", "base", "date", "rates"],
    "additionalProperties": false
}

=== VMatt013/University/Webtech/Gyak5/latest.json
{
    "$schema": "frankfurter-schema.json",
    "amount": 1.0,
    "base": "EUR",
    "date": "2023-10-02",
    "rates": {
        "AUD": 1.6472,
        "BGN": 1.9558,
        "BRL": 5.325,
        "CAD": 1.4335,
        "CHF": 0.9634,
        "CNY": 7.6885,
        "CZK": 24.46,
        "DKK": 7.4585,
        "GBP": 0.86628,
        "HKD": 8.2476,
        "HUF": 388.6,
        "IDR": 16373,
        "ILS": 4.0358,
        "INR": 87.58,
        "ISK": 146.5,
        "JPY": 157.67,
        "KRW": 1427.62,
        "MXN": 18.4533,
        "MYR": 4.967,
        "NOK": 11.3225,
        "NZD": 1.7641,
        "PHP": 59.797,
        "PLN": 4.6123,
        "RON": 4.9748,
        "SEK": 11.5833,
        "SGD": 1.4449,
        "THB": 38.898,
        "TRY": 28.917,
        "USD": 1.053,
        "ZAR": 20.151
    }
}
